apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq-system
spec:
  replicas: 1
  resources:
    requests:
      memory: "500Mi"
      cpu: "300m"
    limits:
      memory: "800Mi"
      cpu: "600m"
  persistence:
    storageClassName: default
    storage: 1Gi
  service:
    type: LoadBalancer
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
    additionalConfig: |
      default_user = user_fiap
      default_pass = pass_fiap
