name: Monitorar alterações no repositório

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você quer monitorar

jobs:
  log-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Mostrar alterações do último commit
      run: |
        echo "Alterações recentes:"
        git log -1 --name-only --pretty=format:"Commit: %h%nAutor: %an%nMensagem: %s%nArquivos alterados:"
